GET http://localhost:8000/api/test
###
GET http://localhost:8000/api/employees
###
POST http://localhost:8000/api/employees
Content-Type: application/json

{
   "first_name": "John",
   "last_name": "Doe",
   "email": "john.doe@example.com",
   "gender": "Male",
   "birthday": "1990-01-01",
   "date_hired": "2020-01-01",
   "salary": 50000
}

### GET http://localhost:8000/api/pensioners
###
POST http://localhost:8000/api/pensioners
Content-Type: application/json 

{
   "serial_number": "SN123456",
   "control_number": "CN654321",
   "first_name": "Jane",
   "middle_name": "A.",
   "last_name": "Smith",
   "pension_account": "PA987654321",
   "rank": "Retired Colonel",
   "bank_name": "Bank of Example",
   "amount_centavos": 1500000,
   "retirement_date": "2025-12-31"
}